/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ljuglaret.versionCnam.Vue;

import javafx.scene.control.Button;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.control.TextField;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.geometry.Pos;
import javafx.scene.Parent;
import javafx.scene.control.Label;


public class VueMvc {
    String styleGlobal =  "-fx-border-radius: 5px;"
    +"-fx-border-width: 1px;"
    + "-fx-border-color: black;"
    +"-fx-background-color:#FFFFFF;"
    +"-fx-padding: 5px;"
    +"-fx-border-insets: 5px;"
    +"-fx-background-insets: 5px;"
    +"-fx-font-size: 20;"; 
    
    private class ButtonGen extends Button{
      
        ButtonGen(String text, double minWidthButton, double minHeightButton, String style){
            this.setText(text);
            this.setMinWidth(minWidthButton);
            this.setMinHeight(minHeightButton);
            this.setStyle(style);

        }

    }

    private class ButtonCh extends ButtonGen{
        ButtonCh(String text){
            super(text, 80, 50,styleGlobal);
        }
    }

    private class ButtonOpe extends ButtonGen{
        ButtonOpe(String text){
            super(text, 70, 40,styleGlobal);
        }
    }


    Label result = new Label("");
    TextField saisieEnCours = new TextField("");
 

String styleB               = styleGlobal;
    Button button0 = new ButtonCh("0" );
    Button button1 = new ButtonCh("1");
    Button button2 = new ButtonCh("2");
    Button button3 = new ButtonCh("3");
    Button button4 = new ButtonCh("4");
    Button button5 = new ButtonCh("5");
    Button button6 = new ButtonCh("6");
    Button button7 = new ButtonCh("7");
    Button button8 = new ButtonCh("8");
    Button button9 = new ButtonCh("9");

    Button buttonRetour = new Button("<=");

    Button buttonParOuvr = new ButtonOpe(" ( ");
    Button buttonParFerm = new ButtonOpe(" ) ");
    Button buttonDiv = new ButtonOpe(" / ");
    Button buttonFois = new ButtonOpe(" * ");
    Button buttonMoins = new ButtonOpe(" -");
    Button buttonPlus = new ButtonOpe(" + ");

    Button buttonEffacer = new Button("C");
    Button buttonEgal = new ButtonOpe("=");
    Button buttonVirgule = new ButtonOpe(",");

    Parent vue;

    public VueMvc() {
        vue = creerVue();
    }

    public Button getButton0() {
        return button0;
    }

    public Button getButton1() {
        return button1;
    }

    public Button getButton2() {
        return button2;
    }

    public Button getButton3() {
        return button3;
    }

    public Button getButton4() {
        return button4;
    }

    public Button getButton5() {
        return button5;
    }

    public Button getButton6() {
        return button6;
    }

    public Button getButton7() {
        return button7;
    }

    public Button getButton8() {
        return button8;
    }

    public Button getButton9() {
        return button9;
    }

    public Button getButtonRetour() {
        return buttonRetour;
    }

    public Button getButtonParOuvr() {
        return buttonParOuvr;
    }

    public Button getButtonParFerm() {
        return buttonParFerm;
    }

    public Button getButtonDiv() {
        return buttonDiv;
    }

    public Button getButtonFois() {
        return buttonFois;
    }

    public Button getButtonPlus() {
        return buttonPlus;
    }

    public Button getButtonMoins() {
        return buttonMoins;
    }

    public Button getButtonEffacer() {
        return buttonEffacer;
    }

    public Button getButtonEgal() {
        return buttonEgal;
    }

    public Button getButtonVirgule() {
        return buttonVirgule;
    }

    public TextField getSaisieEnCours() {
        return saisieEnCours;
    }

    public Label getResult() {
        return result;
    }

    private VBox creerVue() {

        result.setFont(Font.font("Verdana", FontWeight.BOLD, 15));
        saisieEnCours.setFont(Font.font("Verdana", FontWeight.BOLD, 15));

        VBox rootP = new VBox();

        HBox rootH0 = new HBox(10,result);
        rootH0.setAlignment(Pos.BASELINE_CENTER);
        HBox rootH1 = new HBox(10,saisieEnCours);
        rootH1.setAlignment(Pos.BASELINE_CENTER);

        buttonEffacer.setMinWidth(300);
        buttonEffacer.setStyle("-fx-background-color:#FFFFFF;");
        HBox rootH2 = new HBox(10,buttonEffacer,buttonRetour);
        buttonRetour.setStyle("-fx-background-color:#01f0f5;");
        rootH2.setAlignment(Pos.BASELINE_CENTER);
        rootP.getChildren().addAll(rootH0,rootH1,rootH2);

      

        HBox rootH3 = new HBox(
                new VBox(button1,button4,button7, button0,buttonParOuvr),
                new VBox(button2,button5,button8,buttonVirgule,buttonParFerm),
                new VBox(button3,button6,button9,buttonEgal),
                new VBox(buttonPlus,buttonMoins,buttonFois,buttonDiv)
            );
        
        rootH3.setAlignment(Pos.BASELINE_CENTER);

        HBox rootH4 = new HBox();
        rootH4.setAlignment(Pos.BASELINE_CENTER);
       rootP.getChildren().addAll(rootH3,rootH4);
        return rootP;

    }

    public Parent getVue() {
        return vue;
    }

}
